# Generated by Django 6.0.4 on 2026-05-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_phoneverificationcode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='+70000000000', max_length=16, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
