# Generated by Django 6.0.4 on 2026-05-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к доставке'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_coords',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Координаты (Яндекс.Карты)'),
        ),
    ]
