# Generated by Django 6.0.4 on 2026-05-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_delivery_address_order_delivery_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='agreement_accepted',
            field=models.BooleanField(default=False, verbose_name='Согласие с офертой'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидание оплаты'), ('PAID', 'Оплачено'), ('FAILED', 'Ошибка оплаты'), ('CANCELLED', 'Отменено'), ('REFUND_REQUESTED', 'Запрос на возврат'), ('REFUNDED', 'Возврат выполнен')], default='PENDING', max_length=20, verbose_name='Статус'),
        ),
    ]
