# Generated by Django 6.0.4 on 2026-05-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(default='Свежая рыбка с доставкой', verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена (₽)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fish/', verbose_name='Картинка')),
                ('is_secret', models.BooleanField(default=False, verbose_name='Секретный товар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Рыбка',
                'verbose_name_plural': 'Рыбки',
                'ordering': ['name'],
            },
        ),
    ]
