# Generated by Django 6.0.4 on 2026-05-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('freshwater', 'Пресноводные'), ('saltwater', 'Морские'), ('predator', 'Хищные'), ('peaceful', 'Мирные')], default='freshwater', max_length=20, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Новичок'), ('medium', 'Средний'), ('hard', 'Профи')], default='easy', max_length=20, verbose_name='Сложность содержания'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_volume',
            field=models.IntegerField(default=10, verbose_name='Мин. объём аквариума (л)'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=10, verbose_name='Остаток на складе'),
        ),
    ]
