# Generated by Django 6.0.4 on 2026-05-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category_product_difficulty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Аксессуар',
                'verbose_name_plural': '🔧 Аксессуары',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='AquariumProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Аквариум',
                'verbose_name_plural': '🐟 Аквариумы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='FishProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Рыбка',
                'verbose_name_plural': '🐠 Рыбки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
        migrations.CreateModel(
            name='FoodProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Корм',
                'verbose_name_plural': '🍽 Корма',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fish', '🐠 Рыбки'), ('aquarium', '🐟 Аквариумы'), ('accessory', '🔧 Аксессуары'), ('food', '🍽 Корма')], default='fish', max_length=20, verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Товар с доставкой', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('easy', 'Новичок'), ('medium', 'Средний'), ('hard', 'Профи')], default='easy', max_length=20, null=True, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_volume',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='Мин. объём (л)'),
        ),
    ]
